@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml

LAYOUT_WITH_LEGEND()

Container(mobile, "Front-end mobile", "TypeScript / React Native", "Aplicativo móvel onde o usuário irá usufruir das funcionalidades do sistema")
Container(ai, "Inteligência Artificial", "Python / TensorFlow", "Modelo similar com o GPT-3.5 para elaborar os relatórios de investimentos")

ContainerDb(asset_info_doc, "Documento 'AssetInfo'", "MongoDB", "Banco de dados não relacional, porém cada registro tem um atributo 'version' para evitar incosistência ao versionar a API")
ContainerDb(user_doc, "Documento 'User'", "MongoDB", "Banco de dados não relacional, porém cada registro tem um atributo 'version' para evitar incosistência ao versionar a API")

Container_Boundary(backend, "Back-end"){
  Boundary(auth, "Autenticação", "Spring Security"){
    Component(login, "Log-in", "Realiza a verificação do e-mail e senha fornecido pelo usuários com os dados salvos no banco de dados")
    Component(sign_up, "Sign up", "Realiza a criação da conta do novo usuário e envia um e-mail para confirmação")
    Component(reset_passwd, "Redefinição de senha", "Verifica se o e-mail solicitado existe no banco de dados e envia um e-mail de redefinição de senha")
  }
}


System_Ext(yahoo_finance, "Yahoo Finanças", "Serviço para fornecer as informações, indicadores fundamentalistas e notícias de ativos da bolsa de valores.")
System_Ext(google_finance, "Google Finanças", "Serviço para prover as cotações de ativos da bolsa em tempo real")
System_Ext(mail, "Sistema de e-mail", "Sistema de envio de e-mails usando SMTP do Gmail para confirmação de criação de conta e redefinição de senha.", $sprite="envelope")

@enduml