@startuml Quotation Module

!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml

LAYOUT_WITH_LEGEND()

System(mobile, "Front-end mobile", "Aplicativo móvel onde os usuários acessam as funcionalidades do sistema.")
System_Ext(google_finance, "Google Finanças", "Serviço para prover cotações de ativos da bolsa em tempo real.")

ContainerDb_Ext(redis, "Cache", "Redis", "Camada de cache para persistência temporária de dados de cotação do Google Finance.")

Boundary(quotation_module, "Módulo de cotação", "Java"){
  Component(quotation_scrapper, "Extração de cotação", "JSoup", "Extrai o preço e a variação atual dos principais índices do mercado financeiro do Google Finance.")
  Component(quotation_api, "API", "Spring Web", "Expõe os casos de uso de cotação via API REST.")

  Boundary(quotation_usescases, "Casos de uso"){
    Component(get_quotations_usecase, "Obter cotações", "Spring Framework", "Caso de uso para obter os principais índices (IBOV, SMALL, IFIX, S&P500 e Dow Jones).")
  }
}

Rel(mobile, quotation_api, "Faz requisições")
Rel(quotation_scrapper, google_finance, "Extrai dados", "XML/HTTPS")
Rel(get_quotations_usecase, redis, "Consulta cache")
Rel(get_quotations_usecase, quotation_scrapper, "Extrai dados (se não estiver no cache)")
Rel(quotation_api, quotation_usescases, "Executa")

@enduml