@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Context.puml

LAYOUT_WITH_LEGEND()

Person(user, "Usuário", "Pessoa física interagindo com o aplicativo móvel da 3A")

System(3a, "Asset Analysis AI - 3A",  "Plataforma com cursos sobre o mercado financeiro e com uma experiência gamificada. Além disso, após a conclusão de todos os módulos, é liberado uma IA que libera diariamente relatórios de investimentos para auxiliar os investidores nas tomadas de decisão.")

System_Ext(mail, "Sistema de e-mail", "Sistema de envio de e-mails usando SMTP do Gmail para confirmação de criação de conta e redefinição de senha.")
System_Ext(yahoo_finance, "Yahoo Finanças", "Serviço para fornecer as informações, indicadores fundamentalistas e notícias de ativos da bolsa de valores.")
System_Ext(google_finance, "Google Finanças", "Serviço para prover as cotações de ativos da bolsa em tempo real")

Rel(user, 3a, "Usa")
Rel(3a, mail, "Envia e-mail de confirmação ao usuário")
Rel(3a, yahoo_finance, "Consome dados de ativos")
Rel(3a, google_finance, "Obtem cotação")

@enduml
