@startuml Front-end Mobile

!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml

LAYOUT_WITH_LEGEND()

System_Ext(filesystem, "Sistema de arquivo", "Sistema de arquivo para leitura e escrita de arquivos no dispositivo móvel.")
Container_Ext(security_module, "Módulo de segurança", "Java / Spring Security", "Responsável pela autenticação e autorização de usuários via JWT.")
Container_Ext(products_module, "Módulo de produtos", "Java / Spring Web", "Lista produtos e permite criação / edição apenas por administradores.")
Container_Ext(courses_module, "Módulo de cursos", "Java / Spring Web", "Lista módulos e capítulos, obtém progresso do usuário, e permite administração de cursos e módulos por administradores.")
Container_Ext(reports_module, "Módulo de relatórios", "Java / Spring Web", "Permite listagem e solicitação de relatórios por usuários.")
Container_Ext(quotation_module, "Módulo de cotação", "Java / Spring Web / JSoup", "Obtém cotações de índices do mercado financeiro do Google Finance.")

Container_Boundary(mobile, "Front-end mobile"){
  Container(login, "Login", "TypeScript/React Native", "Tela de login onde o usuário informa o endereço de e-mail e senha cadastrados.")
  Container(sigup, "Cadastro", "TypeScript/React Native", "Tela de cadastro onde o usuário fornece seus dados pessoais e confirma a criação da conta por meio de um e-mail de confirmação.")
  Container(profile, "Perfil", "TypeScript/React Native", "Tela de perfil onde são exibidas informações de cadastro e preferências do usuário, armazenadas no dispositivo via shared preferences.")
  Container(home, "Início", "TypeScript/React Native", "Tela inicial responsável por mostrar cotações dos principais índices, capítulo em andamento e últimos relatórios.")
  Container(course, "Cursos", "TypeScript/React Native", "Tela de cursos que lista módulos do curso e o progresso para usuários normais; administradores podem adicionar, editar e excluir módulos e capítulos.")
  Container(report, "Relatórios", "TypeScript/React Native", "Tela de relatórios que lista relatórios de investimento do usuário.")
  Container(product, "Produtos", "TypeScript/React Native", "Tela de produtos que lista produtos liberados com base no nível do usuário.")
}

Rel(login, security_module, "Envia dados de login", "HTTPS/JSON")
Rel(sigup, security_module, "Envia dados de cadastro", "HTTPS/JSON")
Rel(profile, filesystem, "Leitura/Escrita de arquivo")
Rel(home, quotation_module, "Obtém as cotações", "HTTPS/JSON")
Rel(home, courses_module, "Obtém capítulo em andamento", "HTTPS/JSON")
Rel(home, reports_module, "Obtém os últimos relatórios", "HTTPS/JSON")
Rel(course, courses_module, "Obtém os módulos e capítulos", "HTTPS/JSON")
Rel(report, reports_module, "Obtém os relatórios", "HTTPS/JSON")
Rel(product, products_module, "Obtém os produtos", "HTTPS/JSON")

@enduml