@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml

LAYOUT_WITH_LEGEND()

Person(user, "Usuário", "Pessoa física interagindo com o aplicativo móvel da 3A")

System_Boundary(3a, "Asset Analysis AI (3A)"){
  Container(mobile, "Front-end mobile", "Aplicativo móvel onde o usuário irá usufruir das funcionalidades do sistema")
  Container(backend, "Back-end", "Servidor responsável por prover as funcionalidades e armazena todas as regras de negócio do sistema")
  Container(ai, "Inteligência Artificial", "Modelo similar com o GPT-3.5 para elaborar os relatórios de investimentos")
}

System_Ext(mail, "Sistema de e-mail", "Sistema de envio de e-mails usando SMTP do Gmail para confirmação de criação de conta e redefinição de senha.")

Rel(user, mobile, "Usa")

Rel(mobile, backend, "Envio de dados de cadastro ou login", "JSON/HTTPS")
Rel(backend, mobile, "Envio dos dados para a contrução da interface", "JSON/HTTPS")

Rel(backend, mail, "Envia e-mail de confirmação ou redefinição de senha ao usuário")

Rel(backend, ai, "Solicita a criação de um novo relatório de investimento", "JSON/HTTPS")
Rel(ai, backend, "Envia o relatório", "JSON/HTTPS")

@enduml

