@startuml Back-end container

!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml

LAYOUT_WITH_LEGEND()

System(mobile, "Front-end mobile", "Aplicativo móvel onde os usuários acessam as funcionalidades do sistema.")
System_Ext(google_finance, "Google Finanças", "Serviço para prover cotações de ativos da bolsa em tempo real.")

Container_Boundary(backend, "Back-end"){
  Container(security_module, "Módulo de segurança", "Java / Spring Security", "Responsável pela autenticação e autorização de usuários via JWT.")
  Container(products_module, "Módulo de produtos", "Java / Spring Web", "Lista produtos e permite criação / edição apenas por administradores.")
  Container(courses_module, "Módulo de cursos", "Java / Spring Web", "Lista módulos e capítulos, obtém progresso do usuário, e permite administração de cursos e módulos por administradores.")
  Container(reports_module, "Módulo de relatórios", "Java / Spring Web", "Permite listagem e solicitação de relatórios por usuários.")
  Container(quotation_module, "Módulo de cotação", "Java / Spring Web / JSoup", "Obtém cotações de índices do mercado financeiro do Google Finance.")
}

ContainerDb(db, "Banco de dados", "MongoDB", "Banco de dados não relacional; cada registro possui um atributo 'version' para evitar inconsistências ao versionar a API.")
ContainerDb_Ext(redis, "Cache", "Redis", "Camada de cache para persistência temporária de dados de cotação do Google Finance")

Rel(mobile, security_module, "Envia informações de login", "JSON/HTTPS")
Rel(security_module, mobile, "Retorna JWT após autenticação", "JSON/HTTPS")
Rel(security_module, products_module, "Redireciona")
Rel(security_module, courses_module, "Redireciona")
Rel(security_module, reports_module, "Redireciona")
Rel(mobile, quotation_module, "Faz requisição", "JSON/HTTPS")
Rel(quotation_module, redis, "Consulta a cotação")
Rel(quotation_module, google_finance, "Obtém a página HTML crua da cotação", "XML/HTTPS")

BiRel(products_module, db, "Usa")
BiRel(courses_module, db, "Usa")
BiRel(reports_module, db, "Usa")
BiRel(security_module, db, "Usa")

@enduml