name: Generate PlantUML Diagrams

on:
  push:
    paths:
      - '.github/workflows/diagrams.yaml'
      - "**/*.puml"

jobs:
  generate_diagrams:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download PlantUML CLI
        run: |
          curl -LJO https://github.com/plantuml/plantuml/releases/download/v1.2023.10/plantuml-1.2023.10.jar

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: "11"

      - name: Generate Diagrams
        run: |
          # Change 'diagrams/' to your folder containing PlantUML files
          java -jar plantuml-1.2023.10.jar -v -tsvg -o ./assets/diagrams/ "$(find . -type f -name "*.puml")"

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Auto-generated PlantUML diagrams" --author "GitHub Action <action@github.com>"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
